# fly.toml app configuration file generated for av on 2023-06-13T14:37:21-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "av"
primary_region = "dfw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
auto_rollback = true
enable_consul = true
allowed_public_ports = []

[deploy]
release_command = "bash ./scripts/migrate.sh"


[mounts]
source = "av"
destination = "/data"


[env]
FLY_REGION = "dfw"
METRICS_PORT = "8081"
PORT = "8080"
PRIMARY_REGION = "dfw"

[[services]]
# http_checks = []
script_checks = []
protocol = "tcp"
internal_port = 8080
processes = ["app"]

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]

[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20

[[services.tcp_checks]]
interval = "15s"
timeout = "2s"
grace_period = "15s"
restart_limit = 0

[[services.http_checks]]
interval = "10s"
timeout = "2s"
grace_period = "5s"
method = "get"
path = "/healthcheck"
protocol = "http"
tls_skip_verify = false
headers = {}
# [services.http_checks.headers]

[metrics]
port = 8081
path = "/metrics"
